name: Build and push docker images to Azure Container Registry

on:
  workflow_call:
    inputs:
      semver:
        required: true
        type: string
        description: "Target version for the docker image (lowercased)"
      package_name:
        required: true
        type: string
        description: "Package name for the docker image"
      docker_project:
        required: true
        type: string
        description: "Name of the docker project to be built"
      source_folder:
        required: false
        type: string
        default: "src"
        description: "Source folder for the codes in the repository"
      push:
        required: false
        type: boolean
        default: true
        description: "Push the image to the repository"

env:
  PACKAGE_NAME="${{ vars.ACR_SERVER }}/${{ inputs.package_name }}:"
  DOCKER_IMAGE_NAME=${{ github.ref == 'refs/heads/main' && '${{env.PACKAGE_NAME}}${{ inputs.semver }},${{env.PACKAGE_NAME}}latest' || '${{env.PACKAGE_NAME}}${{ inputs.semver }}' }}

jobs:
  build_job:
    name: Build and push the image to ACR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ vars.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push the image to the container registry
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          tags: ${{env.DOCKER_IMAGE_NAME}}
          file: ${{ inputs.source_folder }}/${{ inputs.docker_project }}/Dockerfile
          context: ${{ inputs.source_folder }}
          build-args: |
            VERSION=${{ inputs.semver }}
