name: Build and push docker images to Azure Container Registry

on:
  workflow_call:
    inputs:
      semver:
        required: true
        type: string
        description: "Target version for the docker image (lowercased)"
      package_name:
        required: true
        type: string
        description: "Package name for the docker image"
      docker_project:
        required: true
        type: string
        description: "Name of the docker project to be built"
      source_folder:
        required: false
        type: string
        default: "src"
        description: "Source folder for the codes in the repository"
      push:
        required: false
        type: boolean
        default: true
        description: "Push the image to the repository"
    outputs:
      semver:
        description: "Semantic version number"
        value: ${{ jobs.version_job.outputs.semver }}      
      semver_lowercase:
        description: "Semantic version number in lowercased"
        value: ${{ jobs.version_job.outputs.semver_lowercase }}

jobs:
  build_job:
    name: Build and push the image to ACR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ vars.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push the image to the container registry
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          tags: ${{ format('{0}/{1}:{2}',vars.ACR_SERVER, inputs.package_name, inputs.semver) }}
          file: ${{ inputs.source_folder }}/${{ inputs.docker_project }}/Dockerfile
          context: ${{ inputs.source_folder }}
          build-args: |
            VERSION=${{ inputs.semver }}
