name: Build and publish docker images to Azure Container Registry

on:
  workflow_call:
    inputs:
      semver:
        required: true
        type: string
        description: "Target version for the docker image (lowercased)"
      package_name:
        required: true
        type: string
        description: "Package name for the docker image"
      docker_project:
        required: true
        type: string
        description: "Name of the docker project to be built"
      source_folder:
        required: false
        type: string
        default: "src"
        description: "Source folder for the codes in the repository"

    secrets:
      acr_name:
        required: true
      acr_username:
        required: true
      acr_password:
        required: true

jobs:
  build_job:
    name: Build and push the image to ACR
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.acr_name }}
          username: ${{ secrets.acr_username }}
          password: ${{ secrets.acr_password }}

      - name: Build and push image to the container registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.acr_name }}/${{ inputs.package_name }}:${{ inputs.semver }},${{ secrets.acr_name }}/${{ inputs.package_name }}:latest
          file: ${{ inputs.source_folder }}/${{ inputs.docker_project }}/Dockerfile
          context: ${{ inputs.source_folder }}
          build-args: |
            VERSION=${{ inputs.semver }}
